name: CI Pipeline

on:
  push:                # Ejecutar el flujo cuando se haga un "push" de cambios
    branches:
      - main           # Solo en la rama "main"
  pull_request:        # Ejecutar también en los Pull Requests
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest   # Ejecutar en un sistema Ubuntu

    steps:
      - name: Checkout code  # Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Set up Python  # Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Versión de Python

      - name: Install dependencies  # Instalar dependencias del proyecto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests  # Ejecutar pruebas automatizadas
        run: |
          pytest          # Cambia según el framework que uses
      - name: Run SonarQube analysis
        run: sonar-scanner
