name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Configuración del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar entorno Python (puedes cambiar según tu lenguaje)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Instalar dependencias (si es necesario)
      - name: Install dependencies
        run: |
          pip install pytest

      # Ejecutar pruebas
      - name: Run tests
        run: |
          pytest

      # Ejecutar análisis estático
      - name: Static Code Analysis
        run: |
          pip install pylint
          pylint app.py
